services:
  app:
    build: .
    env_file: .env
    ports:
      - :8000
    networks:
      - app-network
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "error", "--workers", "4"]
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  postgres:
    image: postgres:15
    env_file: .env
    networks:
      - app-network
    ports:
      - :5432
    volumes:
      - ./docker-volumes/user_db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-perl
    ports:
      - "8000:80"
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
