# Generated by Django 5.1.4 on 2024-12-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualphonenumber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Virtual Phone Number', 'verbose_name_plural': 'Virtual Phone Numbers'},
        ),
    ]
