# Generated by Django 5.1.4 on 2024-12-06 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_virtualphonenumber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='virtualphonenumber',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_telephony_verified',
        ),
        migrations.RemoveField(
            model_name='virtualphonenumber',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='virtualphonenumber',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='called_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='caller_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='virtual_phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='api.virtualphonenumber'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='virtualphonenumber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='virtualphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='virtualphonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_numbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
