"""phone number and call log

Revision ID: e19e89b7b5b9
Revises: 7d7fc7d8aa48
Create Date: 2024-12-07 16:56:01.654530

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e19e89b7b5b9"
down_revision: str | None = "7d7fc7d8aa48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "virtual_phone_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(
        op.f("ix_virtual_phone_numbers_id"),
        "virtual_phone_numbers",
        ["id"],
        unique=False,
    )
    op.create_table(
        "call_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number_id", sa.Integer(), nullable=False),
        sa.Column("call_start_time", sa.DateTime(), nullable=True),
        sa.Column("call_duration_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "direction", sa.Enum("INCOMING", "OUTGOING", name="calltype"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["phone_number_id"],
            ["virtual_phone_numbers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_logs_id"), "call_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_logs_id"), table_name="call_logs")
    op.drop_table("call_logs")
    op.drop_index(
        op.f("ix_virtual_phone_numbers_id"), table_name="virtual_phone_numbers"
    )
    op.drop_table("virtual_phone_numbers")
    # ### end Alembic commands ###
