# Generated by Django 5.1.4 on 2024-12-05 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=10, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('Missed', 'Missed Call'), ('Incoming', 'Incoming Call'), ('Outgoing', 'Outgoing Call')], max_length=20)),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('virtual_phone_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.virtualphonenumbers')),
            ],
        ),
    ]
