# Generated by Django 5.1.4 on 2024-12-06 12:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_virtualphonenumbers_virtualphonenumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualphonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='time_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='call_type',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='virtual_phone_num',
        ),
        migrations.RemoveField(
            model_name='virtualphonenumber',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='calllog',
            name='direction',
            field=models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], default=datetime.datetime(2024, 12, 6, 12, 56, 12, 688408, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='phone_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='src.virtualphonenumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualphonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualphonenumber',
            name='number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
