# Generated by Django 5.1.4 on 2024-12-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_user_alter_virtualphonenumber_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
    ]
