# Generated by Django 5.1.4 on 2024-12-14 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtualphoneno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('called_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called_by', to=settings.AUTH_USER_MODEL)),
                ('called_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_no', to='virtualphoneno.virtualphoneno')),
                ('received_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_no', to='virtualphoneno.virtualphoneno')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
            },
        ),
    ]
